const FONT = 'LCD Solid';
const GRAVITY = 600;
const BALL_RADIUS = 20;
const HIT_AREA_RADIUS = 100;
const NEW_BALL_INTERVAL = 5000;
const MAX_INITIAL_SPEED_X = 300;
const TAP_IMPULSE = [600, 900];
const TAP_ANGLE = [60, 120];
const SCORE_FONT_SIZE = 80;
const SCORE_TOP_MARGIN = 20;

export {
  FONT,
  GRAVITY,
  BALL_RADIUS,
  HIT_AREA_RADIUS,
  NEW_BALL_INTERVAL,
  MAX_INITIAL_SPEED_X,
  TAP_IMPULSE,
  TAP_ANGLE,
  SCORE_FONT_SIZE,
  SCORE_TOP_MARGIN,
};
