const FONT = 'LCD Solid';
const GRAVITY = 600;
const BALL_RADIUS = 20;
const HIT_AREA_RADIUS = 50;
const MAX_INITIAL_SPEED_X = 300;
const TAP_IMPULSE = [400, 600];
const TAP_ANGLE = [30, 150];
const SCORE_FONT_SIZE = 80;
const SCORE_TOP_MARGIN = 20;

export {
  FONT,
  GRAVITY,
  BALL_RADIUS,
  HIT_AREA_RADIUS,
  MAX_INITIAL_SPEED_X,
  TAP_IMPULSE,
  TAP_ANGLE,
  SCORE_FONT_SIZE,
  SCORE_TOP_MARGIN,
};
