const INCREASE_SCORE = 'INCREASE_SCORE';
const RESET_SCORE = 'RESET_SCORE';
const START_GAME = 'START_GAME';
const END_GAME = 'END_GAME';

export {
    INCREASE_SCORE,
    RESET_SCORE,
    START_GAME,
    END_GAME,
};
